[package]
name = "local-include"
publish = false
edition = "2021"

[build-dependencies.cxx-qt-extensions-headers]
path = "../cxx-qt-extensions-headers"

[build-dependencies.cxx-qt-lib-headers]
version = "0.6.1"
